development:
  dialect: "postgres"
  database: "augit_development"
  host: "127.0.0.1"
  port: "5432"
  user: "alex"
  password: "password"

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/augit_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
