[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/solarwinds/saml"
  revision = "ee0dd361e78fda6ab73c54308fc1aca06b6b4410"

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/solarwinds/swio-users"
  version = "0.2.0"

[[constraint]]
  name = "github.com/appoptics/appoptics-apm-go"
  version = "1.2.0"

 [[override]]
   name = "github.com/golang/protobuf"
   version = "v1.2.0"
