kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: augit
  namespace: solarwindsio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: augit-server
  template:
    metadata:
      labels:
        app: augit-server
    spec:
      volumes:
        - name: config
          secret:
            secretName: auth-secret
            defaultMode: 420
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: augit-server
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: PORT
              value: ':8080'
            - name: ROOT_URL
              value: 'https://solarwinds.io'
            - name: IDP_METADATA_URL
              valueFrom:
                secretKeyRef:
                  name: augit-idp-url
                  key: value
            - name: CERT_FILE
              value: /config/tls.crt
            - name: KEY_FILE
              value: /config/tls.key
            - name: ENVIRONMENT
              value: production
            - name: COOKIENAME
              valueFrom:
                configMapKeyRef:
                  name: solarwindsio-configs
                  key: cookie-name
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: augit-db
                  key: url
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /config/
          terminationMessagePolicy: File
          image: 'quay.io/solarwinds/augit-server:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: swregcred
      schedulerName: default-scheduler
