kind: Deployment
apiVersion: apps/v1beta2
metadata:
  namespace: solarwindsio
  labels:
    app: augit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: augit-server
  template:
    spec:
      volumes:
        - name: config
          secret:
            secretName: auth-secret
            defaultMode: 420
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: augit-server
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: PORT
              value: ':8080'
            - name: ROOT_URL
              value: 'https://staging.solarwinds.io'
            - name: IDP_METADATA_URL
              value: 'https://swi.okta.com/app/exk1dzsokojGbiGFi1d8/sso/saml/metadata'
            - name: CERT_FILE
              value: /config/tls.crt
            - name: KEY_FILE
              value: /config/tls.key
            - name: ENVIRONMENT
              value: production
            - name: COOKIENAME
              value: staging
            - name: DATABASE_URL
              value: 
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /config/
          terminationMessagePolicy: File
          image: 'quay.io/solarwinds/augit-server:latest'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: swregcred
      schedulerName: default-scheduler
