kind: Service
apiVersion: v1
metadata:
  name: augit-service
  namespace: solarwindsio
  labels:
    app: augit-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
